import type { Profile, Property } from '../engine/types';

export const DEFAULT_PROFILE: Profile = {
  ownIncome: 60000000,
  spouseIncome: 45000000,
  isFirstTime: true,
  spouseHouseHistory: 'none',
  isOver30: true,
  maritalStatus: 'engaged',
  childCount: 0,
  newbornWithin2y: false,
  ownCash: 120000000,
  spouseCash: 60000000,
  existingMonthlyDebt: 0,
  netWorth: 180000000,
  includeSpouseCashBeforeMarriage: false,
  termYears: 30,
  purchaseDate: '2026-11-01',
  priceGrowthRate: 0.03,
  rateAdjust: 0,
  movingAndRepair: 3000000,
};

/** 설계안 §2.4의 예시 매트릭스를 그대로 재현하는 샘플 물건 */
export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: 'sample-changwon',
    name: '창원 A아파트',
    region: 'changwon',
    sigungu: '창원시 성산구',
    price: 380000000,
    areaSqm: 84.9,
    householdCount: 1400,
    builtYear: 2019,
    scores: {
      subwayWalk: 40,
      gtx: 60,
      brt: 5,
      arterialRoad: 7,
      commuteSelf: 20,
      commuteSpouse: 30,
      commuteSeoul: 240,
      jobCenter: 15,
      elemInComplex: 3,
      midHighSchool: 4,
      academyAccess: 4,
      mart: 10,
      hospital: 15,
      park: 4,
      brand: 4,
      parking: 1.3,
      aspect: 4,
      layout: 4,
      futureSupply: 2500,
      populationTrend: 2,
      development: 3,
    },
    penalties: [],
  },
  {
    id: 'sample-busan',
    name: '부산 B아파트',
    region: 'busan',
    sigungu: '부산시 동래구',
    price: 450000000,
    areaSqm: 84.9,
    householdCount: 1800,
    builtYear: 2020,
    scores: {
      subwayWalk: 6,
      gtx: 60,
      brt: 8,
      arterialRoad: 8,
      commuteSelf: 25,
      commuteSpouse: 35,
      commuteSeoul: 300,
      jobCenter: 22,
      elemInComplex: 3,
      midHighSchool: 5,
      academyAccess: 5,
      mart: 8,
      hospital: 12,
      park: 4,
      brand: 5,
      parking: 1.2,
      aspect: 4,
      layout: 4,
      futureSupply: 3200,
      populationTrend: 3,
      development: 4,
    },
    penalties: ['noise'],
  },
  {
    id: 'sample-gyeonggi',
    name: '경기 C아파트',
    region: 'gyeonggi',
    sigungu: '용인시 기흥구',
    price: 520000000,
    areaSqm: 84.9,
    householdCount: 2200,
    builtYear: 2021,
    scores: {
      subwayWalk: 8,
      gtx: 15,
      brt: 6,
      arterialRoad: 6,
      commuteSelf: 45,
      commuteSpouse: 50,
      commuteSeoul: 60,
      jobCenter: 25,
      elemInComplex: 3,
      midHighSchool: 4,
      academyAccess: 4,
      mart: 10,
      hospital: 18,
      park: 4,
      brand: 5,
      parking: 1.1,
      aspect: 4,
      layout: 5,
      futureSupply: 4000,
      populationTrend: 4,
      development: 4,
    },
    penalties: [],
  },
];

export function emptyProperty(id: string): Property {
  return {
    id,
    name: '새 물건',
    region: 'changwon',
    sigungu: '',
    price: 400000000,
    areaSqm: 84.9,
    householdCount: 800,
    builtYear: 2018,
    scores: {},
    penalties: [],
  };
}
